# Generated by Django 5.1.6 on 2025-02-06 10:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('balance', models.DecimalField(decimal_places=18, default=Decimal('0.0'), max_digits=38)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=38)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='transactions.wallet')),
            ],
            options={
                'indexes': [models.Index(fields=['txid'], name='transaction_txid_7f6a8b_idx'), models.Index(fields=['wallet'], name='transaction_wallet__cf6abe_idx')],
            },
        ),
    ]
